apiVersion: backstage.io/v1beta1
kind: Component
metadata:
  name: mywebsite100
  metadata:
  annotations:
    argocd/app-name: mywebsite100
    backstage.io/adr-location: docs/adr
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: mywebsite100
    backstage.io/kubernetes-namespace: mywebsite100
    github.com/project-slug: neenspa/mywebsite100
    janus-idp.io/tekton-enabled: 'true'
  links:
    - url: https://console-openshift-console.apps.democp.vega.local/pipelines/ns/mywebsite100/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.democp.vega.local/k8s/ns/margheproject/deployments/mywebsite100
      title: Deployment
      icon: web
    - url: https://devspaces.apps.democp.vega.local/#https://github.com/neenspa/mywebsite100?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: website
  owner: user:guest
  lifecycle: production
